### ISSUE TITLE
Clean up logs

### ISSUE THREAD

**Issue by eolivelli** [diennea/majordodo#20]
This log is not useful and should be dropped from JVMChannel
{code}
java.lang.Exception: comunication channel closed
	at majordodo.network.jvm.JVMChannel.lambda$null$7(JVMChannel.java:188)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
{code}

**Comment by eolivelli** [comment]
closed with 574bdfff882f5e91c652324561b45aa7b7d6f48b
