### ISSUE TITLE
No LEADER after restart: verify majordodo handling of zk disconnections

### ISSUE THREAD

**Issue by nicoloboschi** [diennea/majordodo#21]
JIRA: https://dev.majordodo.org/jira/browse/MAJ-105

Reporter: alessandro.luccaroni @aluccaroni

After a massive restart of services in a cluster (due to network connection problem) no leader was elected between all of the Brokers (3 brokers). All the broker were up and were in the "Watiting to become leader" state.

{code}
17-09-08-00-22-39       SEVERE Sep 08, 2017 12:22:39 AM majordodo.clientfacade.HttpAPIImplementation doPost
SEVERE: error for {action=beginTransaction}
majordodo.task.LogNotAvailableException: java.lang.Exception: broker_not_leader
        at majordodo.task.Broker.assertBrokerAvailableForClients(Broker.java:555)
        at majordodo.task.Broker.beginTransaction(Broker.java:517)
        at majordodo.clientfacade.ClientFacade.beginTransaction(ClientFacade.java:79)
        at majordodo.clientfacade.HttpAPIImplementation.doPost(HttpAPIImplementation.java:612)
        at majordodo.embedded.EmbeddedBrokerAPIServlet.doPost(EmbeddedBrokerAPIServlet.java:42)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:225)
        at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
        at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: broker_not_leader
        ... 41 more

17-09-08-00-05-18       SEVERE Sep 08, 2017 12:05:18 AM majordodo.task.Broker$1 run
SEVERE: fatal error
java.lang.RuntimeException: majordodo.task.LogNotAvailableException: org.apache.bookkeeper.client.BKException$ZKException
        at majordodo.task.BrokerStatus.followTheLeader(BrokerStatus.java:359)
        at majordodo.task.Broker$1.run(Broker.java:255)
        at java.lang.Thread.run(Thread.java:745)
Caused by: majordodo.task.LogNotAvailableException: org.apache.bookkeeper.client.BKException$ZKException
        at majordodo.replication.ReplicatedCommitLog.followTheLeader(ReplicatedCommitLog.java:1016)
        at majordodo.task.BrokerStatus.followTheLeader(BrokerStatus.java:351)
        ... 2 more
Caused by: org.apache.bookkeeper.client.BKException$ZKException
        at org.apache.bookkeeper.client.SynchCallbackUtils.finish(SynchCallbackUtils.java:63)
        at org.apache.bookkeeper.client.BookKeeper$SyncOpenCallback.openComplete(BookKeeper.java:1354)
        at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:212)
        at org.apache.bookkeeper.client.LedgerOpenOp.operationComplete(LedgerOpenOp.java:121)
        at org.apache.bookkeeper.client.LedgerOpenOp.operationComplete(LedgerOpenOp.java:42)
        at org.apache.bookkeeper.meta.CleanupLedgerManager$CleanupGenericCallback.operationComplete(CleanupLedgerManager.java:52)
        at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:380)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)

17-09-08-00-05-18       SEVERE Sep 08, 2017 12:05:18 AM majordodo.task.Broker brokerFailed
SEVERE: brokerFailed!

17-09-08-00-22-38       SEVERE Sep 08, 2017 12:22:38 AM majordodo.task.Broker <init>
SEVERE: requireAuthentication is set to true

17-09-08-00-22-38       SEVERE Sep 08, 2017 12:22:38 AM majordodo.task.Broker start
SEVERE: Booting Majordodo Broker, version 0.11.0

17-09-08-00-22-38       SEVERE Sep 08, 2017 12:22:38 AM majordodo.task.Broker$1 run
SEVERE: Waiting to become leader...
{code}

**Comment by eolivelli** [comment]
closed with 08eb1cba7f1133a291efb5d3f68c5f0d922a57d8
